### Plotting the LD r2 from PLINK 
###    for the pink panel of 2312 markers
###    
### Garrett McKinney and Carolyn Tarpey | May 2018
### ---------------------------------------

#This R code was originally written by Garrett McKinney to plot the output of PLINK LD r2 for each chromosome. 
#It requires the LD output from PLINK. We used the alignment of the pinks to Chinook to get the Chromosome 
#and position assignments here, so there are 34 Chromosomes, and chromosome 35 are those that aligned to the unassigned 


# #This is the example code that garrett Sent me:
# ggplot()+geom_point(data=LDdata,aes(x=BP_A,y=BP_B,color=R2),shape=15)+scale_color_gradient(low="#E2E2E2",high="dark red")+theme_bw()
# ggplot()+geom_point(data=LDdata[LDdata$R2>=0.3,],aes(x=BP_A,y=BP_B,color=R2),shape=15)+scale_color_gradient(low="black",high="red")+theme_bw()

library(ggplot2)
library(vcfR)
library(stringr)
library(dplyr)
library(gdata)
library(reshape2)
library(plotly)
library(gridExtra)
library(scales) 
library(grid)


#load PLINK LD output files
#### 2312 ALL 
LDdata_chr1 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr1.ld",sep="")
LDdata_chr2 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr2.ld",sep="")
LDdata_chr3 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr3.ld",sep="")
LDdata_chr4 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr4.ld",sep="")
LDdata_chr5 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr5.ld",sep="")
LDdata_chr6 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr6.ld",sep="")
LDdata_chr7 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr7.ld",sep="")
LDdata_chr8 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr8.ld",sep="")
LDdata_chr9 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr9.ld",sep="")
LDdata_chr10<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr10.ld",sep="")
LDdata_chr11<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr11.ld",sep="")
LDdata_chr12<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr12.ld",sep="")
LDdata_chr13<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr13.ld",sep="")
LDdata_chr14<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr14.ld",sep="")
LDdata_chr15<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr15.ld",sep="")
LDdata_chr16<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr16.ld",sep="")
LDdata_chr17<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr17.ld",sep="")
LDdata_chr18<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr18.ld",sep="")
LDdata_chr19<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr19.ld",sep="")
LDdata_chr20<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr20.ld",sep="")
LDdata_chr21<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr21.ld",sep="")
LDdata_chr22<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr22.ld",sep="")
LDdata_chr23<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr23.ld",sep="")
LDdata_chr24<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr24.ld",sep="")
LDdata_chr25<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr25.ld",sep="")
LDdata_chr26<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr26.ld",sep="")
LDdata_chr27<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr27.ld",sep="")
LDdata_chr28<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr28.ld",sep="")
LDdata_chr29<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr29.ld",sep="")
LDdata_chr30<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr30.ld",sep="")
LDdata_chr31<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr31.ld",sep="")
LDdata_chr32<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr32.ld",sep="")
LDdata_chr33<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr33.ld",sep="")
LDdata_chr34<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr34.ld",sep="")
LDdata_chr0 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_ALL_out/Panel_2312_PLINK_out_chr35.ld",sep="")

#assign each of the Chromosomes a plot that will be called later in the grid arrange 
c0<- ggplot()+geom_point(data=LDdata_chr0,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("No matching Alignments") 
c1<- ggplot()+geom_point(data=LDdata_chr1,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 1") 
c2<- ggplot()+geom_point(data=LDdata_chr2,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 2") 
c3<- ggplot()+geom_point(data=LDdata_chr3,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 3") 
c4<- ggplot()+geom_point(data=LDdata_chr4,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 4") 
c5<- ggplot()+geom_point(data=LDdata_chr5,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 5") 
c6<- ggplot()+geom_point(data=LDdata_chr6,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 6") 
c7<- ggplot()+geom_point(data=LDdata_chr7,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 7") 
c8<- ggplot()+geom_point(data=LDdata_chr8,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 8") 
c9<- ggplot()+geom_point(data=LDdata_chr9,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 9") 
c10<- ggplot()+geom_point(data=LDdata_chr10,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 10") 
c11<- ggplot()+geom_point(data=LDdata_chr11,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 11") 
c12<- ggplot()+geom_point(data=LDdata_chr12,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 12") 
c13<- ggplot()+geom_point(data=LDdata_chr13,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 13") 
c14<- ggplot()+geom_point(data=LDdata_chr14,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 14") 
c15<- ggplot()+geom_point(data=LDdata_chr15,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 15") 
c16<- ggplot()+geom_point(data=LDdata_chr16,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 16") 
c17<- ggplot()+geom_point(data=LDdata_chr17,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 17") 
c18<- ggplot()+geom_point(data=LDdata_chr18,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 18") 
c19<- ggplot()+geom_point(data=LDdata_chr19,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 19") 
c20<- ggplot()+geom_point(data=LDdata_chr20,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 20") 
c21<- ggplot()+geom_point(data=LDdata_chr21,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 21") 
c22<- ggplot()+geom_point(data=LDdata_chr22,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 22") 
c23<- ggplot()+geom_point(data=LDdata_chr23,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 23") 
c24<- ggplot()+geom_point(data=LDdata_chr24,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 24") 
c25<- ggplot()+geom_point(data=LDdata_chr25,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 25") 
c26<- ggplot()+geom_point(data=LDdata_chr26,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 26") 
c27<- ggplot()+geom_point(data=LDdata_chr27,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 27") 
c28<- ggplot()+geom_point(data=LDdata_chr28,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 28") 
c29<- ggplot()+geom_point(data=LDdata_chr29,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 29") 
c30<- ggplot()+geom_point(data=LDdata_chr30,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 30") 
c31<- ggplot()+geom_point(data=LDdata_chr31,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 31") 
c32<- ggplot()+geom_point(data=LDdata_chr32,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 32") 
c33<- ggplot()+geom_point(data=LDdata_chr33,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 33") 
c34<- ggplot()+geom_point(data=LDdata_chr34,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 34") 
c35<- ggplot()+geom_point(data=LDdata_chr35,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Unassigned") 


#list the plots and call them in their layout
grid.arrange(c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, 
             c28, c29, c30, c31, c32, c33, c34, c35, top="LD r2 value between pink panel markers assigned to same Chinook chromosome")


#### 2312 Even
#load PLINK LD output files
LD_even_chr1 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr1.ld",sep="")
LD_even_chr2 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr2.ld",sep="")
LD_even_chr3 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr3.ld",sep="")
LD_even_chr4 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr4.ld",sep="")
LD_even_chr5 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr5.ld",sep="")
LD_even_chr6 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr6.ld",sep="")
LD_even_chr7 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr7.ld",sep="")
LD_even_chr8 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr8.ld",sep="")
LD_even_chr9 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr9.ld",sep="")
LD_even_chr10<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr10.ld",sep="")
LD_even_chr11<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr11.ld",sep="")
LD_even_chr12<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr12.ld",sep="")
LD_even_chr13<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr13.ld",sep="")
LD_even_chr14<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr14.ld",sep="")
LD_even_chr15<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr15.ld",sep="")
LD_even_chr16<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr16.ld",sep="")
LD_even_chr17<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr17.ld",sep="")
LD_even_chr18<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr18.ld",sep="")
LD_even_chr19<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr19.ld",sep="")
LD_even_chr20<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr20.ld",sep="")
LD_even_chr21<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr21.ld",sep="")
LD_even_chr22<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr22.ld",sep="")
LD_even_chr23<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr23.ld",sep="")
LD_even_chr24<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr24.ld",sep="")
LD_even_chr25<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr25.ld",sep="")
LD_even_chr26<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr26.ld",sep="")
LD_even_chr27<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr27.ld",sep="")
LD_even_chr28<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr28.ld",sep="")
LD_even_chr29<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr29.ld",sep="")
LD_even_chr30<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr30.ld",sep="")
LD_even_chr31<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr31.ld",sep="")
LD_even_chr32<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr32.ld",sep="")
LD_even_chr33<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr33.ld",sep="")
LD_even_chr34<-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr34.ld",sep="")
LD_even_chr0 <-read.delim("Z:/WORK/TARPEY/Exp_Pink_Pops/Analysis/MarkerSelection/PLINK/2312_Even_out/Panel_2312_Even_out_chr35.ld",sep="")


e0<- ggplot()+geom_point(data=LD_even_chr0 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("No matching Alignments")
e1<- ggplot()+geom_point(data=LD_even_chr1 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 1")
e2<- ggplot()+geom_point(data=LD_even_chr2 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 2")
e3<- ggplot()+geom_point(data=LD_even_chr3 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 3")
e4<- ggplot()+geom_point(data=LD_even_chr4 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 4")
e5<- ggplot()+geom_point(data=LD_even_chr5 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 5")
e6<- ggplot()+geom_point(data=LD_even_chr6 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 6")
e7<- ggplot()+geom_point(data=LD_even_chr7 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 7")
e8<- ggplot()+geom_point(data=LD_even_chr8 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 8")
e9<- ggplot()+geom_point(data=LD_even_chr9 ,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 9")
e10<- ggplot()+geom_point(data=LD_even_chr10,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 10")
e11<- ggplot()+geom_point(data=LD_even_chr11,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 11")
e12<- ggplot()+geom_point(data=LD_even_chr12,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 12")
e13<- ggplot()+geom_point(data=LD_even_chr13,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 13")
e14<- ggplot()+geom_point(data=LD_even_chr14,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 14")
e15<- ggplot()+geom_point(data=LD_even_chr15,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 15")
e16<- ggplot()+geom_point(data=LD_even_chr16,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 16")
e17<- ggplot()+geom_point(data=LD_even_chr17,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 17")
e18<- ggplot()+geom_point(data=LD_even_chr18,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 18")
e19<- ggplot()+geom_point(data=LD_even_chr19,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 19")
e20<- ggplot()+geom_point(data=LD_even_chr20,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 20")
e21<- ggplot()+geom_point(data=LD_even_chr21,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 21")
e22<- ggplot()+geom_point(data=LD_even_chr22,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 22")
e23<- ggplot()+geom_point(data=LD_even_chr23,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 23")
e24<- ggplot()+geom_point(data=LD_even_chr24,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 24")
e25<- ggplot()+geom_point(data=LD_even_chr25,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 25")
e26<- ggplot()+geom_point(data=LD_even_chr26,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 26")
e27<- ggplot()+geom_point(data=LD_even_chr27,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 27")
e28<- ggplot()+geom_point(data=LD_even_chr28,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 28")
e29<- ggplot()+geom_point(data=LD_even_chr29,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 29")
e30<- ggplot()+geom_point(data=LD_even_chr30,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 30")
e31<- ggplot()+geom_point(data=LD_even_chr31,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 31")
e32<- ggplot()+geom_point(data=LD_even_chr32,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 32")
e33<- ggplot()+geom_point(data=LD_even_chr33,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 33")
e34<- ggplot()+geom_point(data=LD_even_chr34,aes(x=BP_A,y=BP_B,color=R2),shape=15, alpha= .35)+ labs(x="", y="") +scale_color_gradient(low="#E2E2E2",high="dark red")+ theme_bw()+ theme(axis.text.x=element_blank(),  axis.ticks.x=element_blank(),axis.text.y=element_blank(), axis.ticks.y=element_blank(), legend.position="none")+ ggtitle("Chr. 34")

#list the plots and call them in their layout
grid.arrange(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, 
             e28, e29, e30, e31, e32, e33, e34, e0, top="LD r2 value between pink panel markers assigned to same ehinook ehromosome")

